import type { CampaignPerformanceRow } from "@/types/campaigns";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const integer = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 0 });
const percent = new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 1, maximumFractionDigits: 2 });

export function CampaignsPerformanceTable({ rows }: { rows: CampaignPerformanceRow[] }) {
  return <section className="rounded-[10px] border border-border bg-card"><div className="border-b border-border px-4 py-3"><h2 className="text-sm font-semibold text-foreground">Desempenho por campanha</h2><p className="mt-1 text-[11px] text-muted-foreground">Métricas persistidas no snapshot atual</p></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left"><thead><tr className="border-b border-border bg-muted text-[10px] font-semibold uppercase tracking-wide text-muted-foreground"><th className="px-4 py-3">Campanha</th><th className="px-3 py-3 text-right">Investimento</th><th className="px-3 py-3 text-right">Impressões</th><th className="px-3 py-3 text-right">Cliques</th><th className="px-3 py-3 text-right">CTR</th><th className="px-3 py-3 text-right">Leads</th><th className="px-3 py-3 text-right">CPL</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${row.name}-${index}`} className="border-b border-border/50 text-[11px] text-muted-foreground hover:bg-muted/70"><td className="px-4 py-4 text-xs font-medium text-foreground">{row.name || "Campanha sem nome"}</td><td className="px-3 py-4 text-right tabular-nums">{money.format(row.investment)}</td><td className="px-3 py-4 text-right tabular-nums">{integer.format(row.impressions)}</td><td className="px-3 py-4 text-right tabular-nums">{integer.format(row.clicks)}</td><td className="px-3 py-4 text-right tabular-nums">{percent.format(row.ctr)}%</td><td className="px-3 py-4 text-right font-semibold tabular-nums text-foreground">{integer.format(row.leads)}</td><td className="px-3 py-4 text-right tabular-nums">{money.format(row.cpl)}</td></tr>)}</tbody></table></div> : <p className="px-4 py-6 text-[11px] text-muted-foreground">Nenhuma campanha com métricas disponível no período.</p>}</section>;
}
